# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/noobie/014.jpg'

# Special
background='#220114'
foreground='#ed8e9b'
cursor='#ed8e9b'

# Colors
color0='#220114'
color1='#490466'
color2='#6D0770'
color3='#A6093A'
color4='#CD0D37'
color5='#94094A'
color6='#93357F'
color7='#ed8e9b'
color8='#a5636c'
color9='#490466'
color10='#6D0770'
color11='#A6093A'
color12='#CD0D37'
color13='#94094A'
color14='#93357F'
color15='#ed8e9b'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
