--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/backgrounds/noobie/014.jpg"

-- Special
background="#220114"
foreground="#ed8e9b"
cursor="#ed8e9b"

-- Colors
color0="#220114"
color1="#490466"
color2="#6D0770"
color3="#A6093A"
color4="#CD0D37"
color5="#94094A"
color6="#93357F"
color7="#ed8e9b"
color8="#a5636c"
color9="#490466"
color10="#6D0770"
color11="#A6093A"
color12="#CD0D37"
color13="#94094A"
color14="#93357F"
color15="#ed8e9b"
